### ISSUE TITLE
Gorgiana Molloy collected only under her married name

### ISSUE THREAD

**Issue by MargaretRDonald** [dshorthouse/bloodhound#151]
I would like to be able to exclude the hundreds of pages of G. Kennedy s (rather than having to see each batch of 25 Kennedys  and hitting the "Not Them" button) Is this possible?

**Comment by dshorthouse** [comment]
Would you be ok with attributing specimens via a csv file? There's a column entitled, "Not me" and if you put TRUE as values in those cells, you'll be able to do this is bulk through copy/paste rather than through clicks.

Another way of doing this is to use the "Advanced Search & Filter" feature on the Discovered tab of the Helping interface. Through that page, there is a way to search for a particular agent like "G. Kennedy", choose it, and then see the result in the Discovered tab. You would have something like this: https://bloodhound-tracker.net/help-others/Q5548105?agent_id=199189&per=250. 32 pages to bulk click "Not me" is a tad faster.

Or, are you asking for a way to effectively hide pages as a surrogate to having chosen "Not me"? If so, I wish that were possible. Data from GBIF are refreshed every few weeks. There are newly transcribed and published data all the time. Some of these are existing records with updated metadata. A blanket exclusion would surely catch some legitimately assignable records unless I had a mechanism to display new records since the last refresh.

**Comment by dshorthouse** [comment]
Does the solution work for you, Margaret? If so, please let me know if this ticket can be closed.

**Comment by MargaretRDonald** [comment]
Dear David
I have now managed to find the download button which would be perfect in
the case of the person for whom I know I have made errors in attribution
(but whose profile isn't public).
For Georgiana Molloy, however, it downloads the specimens attributed only
and not all the G. Kennedys, so there seems no other way to go about the
task than to tackle all 641 pages of Kennedys (mixed perhaps with a tine
fraction of Molloys). so currently I am putting it off, as it is not an
attractive proposition.
Thanks very much for your help. And I think you can close the issue.
Regards,
Margaret

Margaret Donald BA (Hon), M. App Stat, Ph.D, AStat
Statistician, Anne Clements & Associates

**Comment by dshorthouse** [comment]
Closing for now but suspect some of the issue can be resolved with the ability to sort & filter columns, both are desirable features.

**Comment by MargaretRDonald** [comment]
Yes. Sorting and filtering on columns would make a huge change in the ease
of all the work.
Cheers. Margaret
