### ISSUE TITLE
Extract agent_utility to its own gem.

### ISSUE THREAD

**Issue by mjy** [dshorthouse/bloodhound#16]
As a developer I want to re-use that code and test suite.

**Comment by dshorthouse** [comment]
TOTALLY agree and it's the reason I dumped that stuff there along with some rudimentary tests because I had an inkling that it eventually needed a dedicated home. But that self.clean method, meant to do some cleansing peculiar to our domain really & truly sucks. The ifs and returns & those REGEX bits make my head hurt. And what scares me is that I've done near nothing with different cultural representations of names; the Namae gem itself is pretty good, but not perfect. Ultimately this agent_utility stuff is a like a nasty pre-sweep of cruft before passing it to Namae. I'll reach out to @inukshuk to see if he has any suggestions. He may have ideas on how to to deal with really messy content where the approach may require methods akin to entity extraction prior to parsing.

**Comment by mjy** [comment]
I think it might help to start envisioning the extraction code as part of a ongoing curatorial process, rather than a one off.  For example, given 100k records the code might initially find X successfully, or a curator might start manually parsing the data as well.  The regex/ifs etc. perhaps only need to get you started and act as training before alternative approaches (AI?!) become be more useful.  Regardless, in a dynamic system, over time-

* With each decision the system "learns", and improves. We found that in large datasets simply finding exact matches from each manual decision is super useful. 
* With related decisions (extracting other pieces of the collecting event or surrounding text via related tools for lat long, dates, etc) the text input gets smaller, and therefor easier to parse. Play off the different parsers against each other.
* We should be able to create fairly large training sets from collecting events that include verbatim text and extracted, labelled text.  Where do these experiments exist elsewhere?

**Comment by dshorthouse** [comment]
Here's a start: https://rubygems.org/gems/dwc_agent
