### ISSUE TITLE
A couple more missing profiles?

### ISSUE THREAD

**Issue by kcopas** [dshorthouse/bloodhound#77]
A couple more names that I'd expect to show up—just flagging them in the event there's any systemic reason they're not:
+ [Alice Tryon](https://en.wikipedia.org/wiki/Alice_F._Tryon)
+ [Alice Haskins](https://en.wikipedia.org/wiki/Alice_Haskins)
+ [Frank Nicholas Meyer](https://en.wikipedia.org/wiki/Frank_Nicholas_Meyer)

**Comment by dshorthouse** [comment]
Thanks, @kcopas. I pull from wikidata only if there are birth and death dates accurate to the day. And, the SPARQL query to find people (executed once a day) searches for a handful of properties. These are [IPNI Author ID](https://www.wikidata.org/wiki/Property:P586), [Harvard Index of Botanists](https://www.wikidata.org/wiki/Property:P6264), [Entomologists of the World](https://www.wikidata.org/wiki/Property:P5370), [BHL Creator ID](https://www.wikidata.org/wiki/Property:P4081), and [ZooBank Author ID](P2006). The two Alices and Frank were either missing dates of birth/death or my SPARQL query didn't find them. I've since adjusted these in wikidata and they're also now in Bloodhound.

**Comment by kcopas** [comment]
Thanks, @dshorthouse. I did know from a previous issue that I should look for precise dates (still bummed that von Siebold’s collaborator Heinrich Bürger will fail on that score), but I looked and thought they were in place for this trio.

Thanks for whatever bit of magic worked in the end!

**Comment by dshorthouse** [comment]
Wikipedia and wikidata are separate entities and there are occasional discrepancies between the two. I'll *eventually* expose my copy/paste interface to import wikidata or ORCID profiles - just have to figure out where and how that would make sense. It's a very complex interface :)~

![Screen Shot 2019-07-16 at 10 26 08 AM](https://user-images.githubusercontent.com/326459/61302740-4b40ca80-a7b4-11e9-99a6-3b521c5b4da0.png)
