### ISSUE TITLE
Correcting/curating mistakes

### ISSUE THREAD

**Issue by kcopas** [dshorthouse/bloodhound#81]
While I know my work in this system should simply be flawless, I have fallen short at times. On most occasions—and this happened more early on in the experiment, when I was still becoming accustomed to the UI—I'd punch the wrong button as the UI jumped up from the bottom of the page. However, at other times, I've just fat-fingered the flag when I meant to hit the microscope, or vice versa, or both, or whatever—it's just a mistake. 

I don't think you need anything like an undo button (which I suspect would be annoying to develop), but it would be nice to have a way to correct erroneous claims. I haven't posted anything about this, though, until I had an example of a clearly identifiable error. 

I love the network feature for what it reveals about the various chains of connection across scientific generations, and for what it shows about monumental collectors, who continue to provide others with material to work with decades and even centuries after they're gone. It's also a way to see the importance of under-valued and forgotten contributors and their connections to others who are far more prominent. Which brings me to my example of a misattribution.

[Argentinan botanist Alicia Lourteig could not have collected with 18th-century French explorer Nicolas Baudin](https://bloodhound-tracker.net/Q454806/co-collectors). Downloading her csv, though, I've found evidence of a mistake in my work on Baudin's profile, which erroneously claims a [Brazilian specimen collected by French explorer etc. August Saint Hillaire](https://www.gbif.org/occurrence/439204334) that Lourteig did identify. I don't know how or why the error came in, but there it is.

Apologies, again, for being less than perfect in this, but is it possible to devise a simple way of addressing such mistakes? This traces back to your list items 3 & 4 in #65 .

**Comment by kcopas** [comment]
It's embarrassing to note that the record I've highlighted actually two errors (something the Firefox extension just turned up).

Not only did Baudin not collect it—neither did Lourteig (she identified it).
<img width="724" alt="Screenshot 2019-07-28 at 11 42 57" src="https://user-images.githubusercontent.com/12379236/62004988-e6c72900-b12c-11e9-858b-b955daba43dc.png">

**Comment by dshorthouse** [comment]
I tidied the claims on https://www.gbif.org/occurrence/439204334 as well as https://www.gbif.org/occurrence/1212569289. The latter means Alicia Lourteig is no longer indicated as a co-collector of Nicolas Baudin.

There are number of items to contend with here.

First, you're correct in that an undo button wouldn't be an appropriate function here. There's bulk claim and single claim so does that require bulk undo and single undo? Does that then mean a bulk and single redo? Bleh. This has the potential to get out of hand.

Second, there's the matter of where and how errors are discovered. These could be quite heterogeneous. Errors might be discovered in network associations, they might be discovered via the rudimentary map, via the browser extensions, or elsewhere, even within the csv downloads.

I've been reluctant to create a view of individual occurrence records because they can be unstable via successive harvests (see https://github.com/gbif/portal-feedback/issues/2064) and chose instead to link to GBIF occurrences. The full record is there to view whereas only a small subset of the DwC fields are included in Bloodhound. This will lead to many seemingly erroneous links from Bloodhound to GBIF, but it's because the former is a couple weeks behind the latter where record has unfortunately disappeared.

So...

It seems we need an occurrence view in Bloodhound. It's getting harder to escape it. And, we'll need links to this view from elsewhere in Bloodhound so we can add/edit/remove claims as needed.

I'll close this ticket and make a new one for this occurrence view with add/edit/remove claims.
