### ISSUE TITLE
Nathaniel Lord Britton: MIA

### ISSUE THREAD

**Issue by kcopas** [dshorthouse/bloodhound#90]
I'm probably overlooking some feature, but no profile is emerging for the founder of the NYBG, Nathaniel Lord Britton, even though he has a [Wikidata page](https://www.wikidata.org/wiki/Q553714).

His wife, bryologist [Elizabeth Gertrude Britton](https://bloodhound-tracker.net/Q2567402), appears to have no such problem.

**Comment by dshorthouse** [comment]
Good catch! It's the "Lord" as a middle name that threw off the parser. I've updated it and will manually add Britton.

**Comment by dshorthouse** [comment]
Gack, I wrote too soon by typing "will manually add Britton". Production code is a few steps behind development because of an unrelated issue (developers of dependencies like to break things in the name of progress) and I need a few more days to sort out that issue before the new version of the gem is on production.
